"""
M7 补充 — Step-back Prompting Test

Run from LangGraphLearning/:
    .venv/bin/python tests/rag/test_m7_7_stepback.py

Comparison per query:
  [Dense@3 baseline]        direct query embedding, top-3
  [Dense@20 → Reranked]     M7.3: section-level + reranking
  [StepBack → Reranked]     original + abstract query → merge → rerank

The abstract (step-back) question generated by GLM is printed under each
query so you can judge whether the LLM moved up in abstraction correctly.
"""

import sys
sys.path.insert(0, ".")

from src.rag.chunker import chunk_by_section
from src.rag.vector_store import VectorStore
from src.rag.reranker import Reranker
from src.rag.stepback_retriever import StepBackRetriever

ACT_TEXT_FILE = "tests/rag/health_services_act.txt"
COLLECTION    = "health-services-act-baseline"
CANDIDATE_N   = 20
FINAL_K       = 3

TEST_QUERIES = [
    "mandatory reporting obligations for health practitioners",
    "penalty for providing false information",
    "minister's power to make regulations",
    "patient rights and complaints procedure",
]


def print_table(label: str, results: list[dict], score_key: str) -> None:
    col_sec   = 18
    col_title = 40
    col_score = 8
    col_prev  = 6
    sep = f"+{'─'*4}+{'─'*col_sec}+{'─'*col_title}+{'─'*col_score}+{'─'*col_prev}+"
    print(f"  [{label}]")
    print(f"  {sep}")
    print(f"  │{'Rank':^4}│{'Section':^{col_sec}}│{'Title':^{col_title}}│{'Score':^{col_score}}│{'Prev':^{col_prev}}│")
    print(f"  {sep}")
    for rank, r in enumerate(results, 1):
        section = r["chunk_id"][:col_sec - 1]
        title   = r["title"][:col_title - 1]
        score   = f"{r.get(score_key, 0):.3f}"
        prev    = str(r.get("prev_rank", "-"))
        print(f"  │{rank:^4}│{section:<{col_sec}}│{title:<{col_title}}│{score:^{col_score}}│{prev:^{col_prev}}│")
    print(f"  {sep}")


def main():
    print("Loading Act and building index...\n")
    with open(ACT_TEXT_FILE, encoding="utf-8") as f:
        act_text = f.read()
    chunks = chunk_by_section(act_text)

    store = VectorStore(collection_name=COLLECTION, persist_dir="./chroma_db")
    if store.count() != len(chunks):
        store.reset()
        store.add_chunks(chunks)
    else:
        print(f"  Reusing {store.count()} indexed chunks\n")

    reranker = Reranker()
    sb       = StepBackRetriever(vector_store=store, reranker=reranker)

    print("\n" + "=" * 75)
    print("Comparison: Dense@3  vs  Dense@20→Reranked  vs  StepBack→Reranked")
    print("=" * 75)

    for i, query in enumerate(TEST_QUERIES, 1):
        print(f"\nQuery {i}: \"{query}\"")

        # Dense top-3 baseline
        dense3 = store.search(query, top_k=FINAL_K)
        print_table("Dense@3 baseline", dense3, "score")

        # Dense top-20 → rerank
        dense20 = store.search(query, top_k=CANDIDATE_N)
        for rank, r in enumerate(dense20, 1):
            r["prev_rank"] = rank
        dense_reranked = reranker.rerank(query, dense20, top_k=FINAL_K)
        print_table(f"Dense@{CANDIDATE_N} → Reranked", dense_reranked, "rerank_score")

        # Step-back → rerank
        print(f"  [Calling GLM to generate step-back query...]")
        sb_reranked, abstract_query = sb.search(
            query, per_query_k=CANDIDATE_N, final_k=FINAL_K
        )
        print(f"  Abstract query: \"{abstract_query}\"")
        print_table("StepBack → Reranked", sb_reranked, "rerank_score")


if __name__ == "__main__":
    main()
